FROM tensorflow/tensorflow:2.5.1
RUN apt-get update && apt-get install -y python3.7 python3.7-dev libsasl2-modules libsasl2-dev

WORKDIR /app
ADD tpfy/requirements.txt /app
RUN python3.7 -m pip install --upgrade pip && python3.7 -m pip install -r requirements.txt && python3.7 -m pip freeze
ENTRYPOINT sh
