# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tpfy_predict_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18tpfy_predict_event.proto"|\n\x11TpfyFeatureVector\x12\x0c\n\x04\x66ids\x18\x01 \x03(\x03\x12\x15\n\rweighted_fids\x18\x02 \x03(\x03\x12\x13\n\x0b\x66id_weights\x18\x03 \x03(\x02\x12\x16\n\x0esparse_indices\x18\x04 \x03(\x05\x12\x15\n\rsparse_values\x18\x05 \x03(\x02"p\n\x05Watch\x12\x12\n\ncontent_id\x18\x01 \x01(\t\x12\x13\n\x0blanguage_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x17\n\x0f\x66irst_timestamp\x18\x04 \x01(\x03\x12\x12\n\nwatch_time\x18\x05 \x01(\x05"2\n\x0cInstalledApp\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t"\xb7\x02\n\nRawFeature\x12\x1b\n\x0b\x65nt_watches\x18\x01 \x03(\x0b\x32\x06.Watch\x12\x19\n\x11\x65nt_watch_weights\x18\x02 \x03(\x02\x12!\n\x03lpv\x18\x03 \x03(\x0b\x32\x14.RawFeature.LpvEntry\x12%\n\x0einstalled_apps\x18\x04 \x03(\x0b\x32\r.InstalledApp\x12@\n\x13serialized_features\x18\x63 \x03(\x0b\x32#.RawFeature.SerializedFeaturesEntry\x1a*\n\x08LpvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a\x39\n\x17SerializedFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01"n\n\x12TpfyPredictPayload\x12(\n\x0cuser_feature\x18\x01 \x01(\x0b\x32\x12.TpfyFeatureVector\x12 \n\x0braw_feature\x18\x02 \x01(\x0b\x32\x0b.RawFeature\x12\x0c\n\x04\x63ms3\x18\x03 \x01(\x08"\xba\x02\n\x10TpfyPredictEvent\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0f\n\x07\x64w_p_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x10\n\x08platform\x18\x04 \x01(\t\x12\x0f\n\x07page_id\x18\x06 \x01(\t\x12\x1a\n\x12subscription_types\x18\x07 \x03(\t\x12\x32\n\tab_groups\x18\x08 \x03(\x0b\x32\x1f.TpfyPredictEvent.AbGroupsEntry\x12\x19\n\x11tpfy_request_type\x18\t \x01(\x05\x12\x0f\n\x07payload\x18\n \x01(\x0c\x12\x12\n\ndebug_info\x18\x0b \x01(\t\x12\r\n\x05\x66lags\x18\x0c \x01(\x03\x1a/\n\rAbGroupsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
)


_TPFYFEATUREVECTOR = DESCRIPTOR.message_types_by_name["TpfyFeatureVector"]
_WATCH = DESCRIPTOR.message_types_by_name["Watch"]
_INSTALLEDAPP = DESCRIPTOR.message_types_by_name["InstalledApp"]
_RAWFEATURE = DESCRIPTOR.message_types_by_name["RawFeature"]
_RAWFEATURE_LPVENTRY = _RAWFEATURE.nested_types_by_name["LpvEntry"]
_RAWFEATURE_SERIALIZEDFEATURESENTRY = _RAWFEATURE.nested_types_by_name[
    "SerializedFeaturesEntry"
]
_TPFYPREDICTPAYLOAD = DESCRIPTOR.message_types_by_name["TpfyPredictPayload"]
_TPFYPREDICTEVENT = DESCRIPTOR.message_types_by_name["TpfyPredictEvent"]
_TPFYPREDICTEVENT_ABGROUPSENTRY = _TPFYPREDICTEVENT.nested_types_by_name[
    "AbGroupsEntry"
]
TpfyFeatureVector = _reflection.GeneratedProtocolMessageType(
    "TpfyFeatureVector",
    (_message.Message,),
    {
        "DESCRIPTOR": _TPFYFEATUREVECTOR,
        "__module__": "tpfy_predict_event_pb2"
        # @@protoc_insertion_point(class_scope:TpfyFeatureVector)
    },
)
_sym_db.RegisterMessage(TpfyFeatureVector)

Watch = _reflection.GeneratedProtocolMessageType(
    "Watch",
    (_message.Message,),
    {
        "DESCRIPTOR": _WATCH,
        "__module__": "tpfy_predict_event_pb2"
        # @@protoc_insertion_point(class_scope:Watch)
    },
)
_sym_db.RegisterMessage(Watch)

InstalledApp = _reflection.GeneratedProtocolMessageType(
    "InstalledApp",
    (_message.Message,),
    {
        "DESCRIPTOR": _INSTALLEDAPP,
        "__module__": "tpfy_predict_event_pb2"
        # @@protoc_insertion_point(class_scope:InstalledApp)
    },
)
_sym_db.RegisterMessage(InstalledApp)

RawFeature = _reflection.GeneratedProtocolMessageType(
    "RawFeature",
    (_message.Message,),
    {
        "LpvEntry": _reflection.GeneratedProtocolMessageType(
            "LpvEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _RAWFEATURE_LPVENTRY,
                "__module__": "tpfy_predict_event_pb2"
                # @@protoc_insertion_point(class_scope:RawFeature.LpvEntry)
            },
        ),
        "SerializedFeaturesEntry": _reflection.GeneratedProtocolMessageType(
            "SerializedFeaturesEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _RAWFEATURE_SERIALIZEDFEATURESENTRY,
                "__module__": "tpfy_predict_event_pb2"
                # @@protoc_insertion_point(class_scope:RawFeature.SerializedFeaturesEntry)
            },
        ),
        "DESCRIPTOR": _RAWFEATURE,
        "__module__": "tpfy_predict_event_pb2"
        # @@protoc_insertion_point(class_scope:RawFeature)
    },
)
_sym_db.RegisterMessage(RawFeature)
_sym_db.RegisterMessage(RawFeature.LpvEntry)
_sym_db.RegisterMessage(RawFeature.SerializedFeaturesEntry)

TpfyPredictPayload = _reflection.GeneratedProtocolMessageType(
    "TpfyPredictPayload",
    (_message.Message,),
    {
        "DESCRIPTOR": _TPFYPREDICTPAYLOAD,
        "__module__": "tpfy_predict_event_pb2"
        # @@protoc_insertion_point(class_scope:TpfyPredictPayload)
    },
)
_sym_db.RegisterMessage(TpfyPredictPayload)

TpfyPredictEvent = _reflection.GeneratedProtocolMessageType(
    "TpfyPredictEvent",
    (_message.Message,),
    {
        "AbGroupsEntry": _reflection.GeneratedProtocolMessageType(
            "AbGroupsEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _TPFYPREDICTEVENT_ABGROUPSENTRY,
                "__module__": "tpfy_predict_event_pb2"
                # @@protoc_insertion_point(class_scope:TpfyPredictEvent.AbGroupsEntry)
            },
        ),
        "DESCRIPTOR": _TPFYPREDICTEVENT,
        "__module__": "tpfy_predict_event_pb2"
        # @@protoc_insertion_point(class_scope:TpfyPredictEvent)
    },
)
_sym_db.RegisterMessage(TpfyPredictEvent)
_sym_db.RegisterMessage(TpfyPredictEvent.AbGroupsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _RAWFEATURE_LPVENTRY._options = None
    _RAWFEATURE_LPVENTRY._serialized_options = b"8\001"
    _RAWFEATURE_SERIALIZEDFEATURESENTRY._options = None
    _RAWFEATURE_SERIALIZEDFEATURESENTRY._serialized_options = b"8\001"
    _TPFYPREDICTEVENT_ABGROUPSENTRY._options = None
    _TPFYPREDICTEVENT_ABGROUPSENTRY._serialized_options = b"8\001"
    _TPFYFEATUREVECTOR._serialized_start = 28
    _TPFYFEATUREVECTOR._serialized_end = 152
    _WATCH._serialized_start = 154
    _WATCH._serialized_end = 266
    _INSTALLEDAPP._serialized_start = 268
    _INSTALLEDAPP._serialized_end = 318
    _RAWFEATURE._serialized_start = 321
    _RAWFEATURE._serialized_end = 632
    _RAWFEATURE_LPVENTRY._serialized_start = 531
    _RAWFEATURE_LPVENTRY._serialized_end = 573
    _RAWFEATURE_SERIALIZEDFEATURESENTRY._serialized_start = 575
    _RAWFEATURE_SERIALIZEDFEATURESENTRY._serialized_end = 632
    _TPFYPREDICTPAYLOAD._serialized_start = 634
    _TPFYPREDICTPAYLOAD._serialized_end = 744
    _TPFYPREDICTEVENT._serialized_start = 747
    _TPFYPREDICTEVENT._serialized_end = 1061
    _TPFYPREDICTEVENT_ABGROUPSENTRY._serialized_start = 1014
    _TPFYPREDICTEVENT_ABGROUPSENTRY._serialized_end = 1061
# @@protoc_insertion_point(module_scope)
